//SignUp
export const SIGN_UP_TEXT_CHANGED = 'SIGN_UP_TEXT_CHANGED';
export const SIGN_UP_SET_ERREUR = 'SIGN_UP_SET_ERREUR';
export const SIGN_UP_START_LOADER = 'SIGN_UP_START_LOADER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_INITIAL_STATE = 'SIGN_UP_INITIAL_STATE';
//SignIn
export const SIGN_IN_EMAIL_CHANGED = 'SIGN_IN_EMAIL_CHANGED';
export const SIGN_IN_PASSWORD_CHANGED = 'SIGN_IN_PASSWORD_CHANGED';
export const SIGN_IN_LOGIN_USER_SUCCESS = 'SIGN_IN_LOGIN_USER_SUCCESS';
export const SIGN_IN_START_LOADER = 'SIGN_IN_START_LOADER';
export const SIGN_IN_SET_ERREUR = 'SIGN_IN_SET_ERREUR';
export const SIGN_IN_INITIAL_STATE = 'SIGN_IN_INITIAL_STATE';
export const ON_SIGN_OUT = 'ON_SIGN_OUT';
//ForgetPassword
export const FORGET_PASSWORD_EMAIL_CHANGED = 'FORGET_PASSWORD_EMAIL_CHANGED';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_START_LOADER = 'FORGET_PASSWORD_START_LOADER';
export const FORGET_PASSWORD_SET_ERREUR = 'FORGET_PASSWORD_SET_ERREUR';
export const FORGET_PASSWORD_INITIAL_STATE = 'FORGET_PASSWORD_INITIAL_STATE';
//AppLoading
export const SET_USER_IN_REDUCER = 'SET_USER_IN_REDUCER';
export const IS_CONNECTED_APP = 'IS_CONNECTED_APP';
export const IS_REFRESH_CONNECTED_APP = 'IS_REFRESH_CONNECTED_APP';
//Home
export const HOME_START_LOADER = 'HOME_START_LOADER';
export const HOME_GET_PUBLICATIONS_SUCCESS = 'HOME_GET_PUBLICATIONS_SUCCESS';
export const HOME_START_REFRESHING = 'HOME_START_REFRESHING';
export const HOME_FIRST_GET_PUBLICATIONS_SUCCESS = 'HOME_FIRST_GET_PUBLICATIONS_SUCCESS';
